run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - copyloopvar
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - gocritic
  - godot
  - gofmt
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nilerr
  - noctx
  - nolintlint
  - nosprintfhostport
  - revive
  - staticcheck
  - unconvert
  - unused
  - usestdlibvars
  - whitespace

linters-settings:
  revive:
    rules:
    # That is just how the Kubernetes code-generators are written.
    # We'd rather stay closer to upstream than fixing this.
    - name: unexported-return
      disabled: true
